# Extracción de datos

## Formato
El PDB ofrece descargar sus archivos en tres formatos diferentes: `.xml`, `.pdb` y `.mmcif`. El segundo es el más fácil de leer y manipular; sin embargo, se decidió usar el tercer formato debido al siguiente párrafo:

> Many of the errors have been fixed in the equivalent mmCIF files. Hence, if you are interested in the header information, it is a good idea to extract information from mmCIF files...
>
> De <https://biopython.readthedocs.io/en/latest/chapter_pdb.html>.

El formato `.mmcif` se detalla en <http://mmcif.wwpdb.org/>. Existe una correspondencia entre las etiquetas del `.pdb` con las etiquetas del `.mmcif`.

## Descarga
Para descargar todo las estructuras del PDB en formato `.mmcif`, se usa el siguiente comando:

```{bash, eval=FALSE}
cd /run/media/murphy/lolita/doctorado
rsync -avPz --delete data.pdbjbk1.pdbj.org::ftp_data/structures/divided/mmCIF/ ./mmCIF
# Tarda entre 5 y 6 horas con una buena conexión de internet.
```

> Instrucciones de <https://www.wwpdb.org/ftp/pdb-ftp-sites>.

## Organización de archivos
Los archivos están organizados en diferentes subdirectorios, cuyo nombre está formado por el segundo y el tercer carácter del nombre del mismo archivo. Por ejemplo `1abc.mmcif` estará en el subdirectorio `ab/`. Se realiza una copia de los archivos en un solo directorio en el disco duro con dos objetivos en mente: tener un respaldo y manipular de una manera más sencilla los archivos.

```{bash, eval=FALSE}
cd /run/media/murphy/lolita/doctorado
mkdir mmCIF_backup
cd mmCIF/
time find . -name '*.gz' -exec cp \{\} /run/media/murphy/lolita/doctorado/mmCIF_backup/ \; 
# Esto tarda toda la  mañana... no sé por qué! 
```

### Separa entradas por método experimental
De los archivos depositados en el PDB, obtenemos aquellas estructuras determinadas únicamente por difracción de rayos-X de cristales. Este se puede considerar como el primer filtro. Además ayuda a eliminar confusiones posteriores. 

> El problema es que `gemmi` extrae etiquetas de manera excelente, pero no conoce contextos. Esto puede resultar, dependiendo de las etiquetas, en datos incompletos. 

```{bash, eval=FALSE}
cd /run/media/murphy/lolita/doctorado/
mkdir xray
time gemmi grep _exptl.method mmCIF_backup/ > xray/method.list
# Esto tarda 155 minutos
# Se confirma con:
# wc -l method.dat
# 190846 
# La diferencia con el total de entradas en el PDB (190639), es por los pdbs obtenidos vía múltiples métodos.
# La siguiente línea nos da donde se da esta diferencia.
# awk -F ":" '{print $1}' method.dat | uniq -c | awk '{ if ($1!="1") print $0}' | wc -l
# 205
# Lo cual se confirma en la búsqueda avanzada del PDB escogiendo como método experimental "Múltiples métodos"
cd /run/media/murphy/lolita/doctorado/xray/
grep X-RAY method.list | awk -F : '{print $1}' | tr '[:upper:]' '[:lower:]' > pdbs_by_xray.list
sed 's/$/.cif.gz/'g pdbs_by_xray.list > list_pdbs_by_xray
# Es interesante comparar el total de entradas en el PDB con aquellas obtenidas por difracción de rayos X:
# wc -l pdbs_by_xray.dat
# 165662 
mkdir entries
time cat list_pdbs_by_xray | while read line;
do cp /run/media/murphy/lolita/doctorado/mmCIF_backup/$line entries/; done 
# Esto tarda 145 minutos.
```

## Extracción de datos
```{bash, eval=FALSE}
# Usar un delimitador que no aparece en los archivos.
cd /run/media/murphy/lolita/doctorado/xray/
time gemmi grep --delimiter='¿' _entity_poly.entity_id -a _entity_poly.type -a _struct_ref.pdbx_db_accession -a _entity.pdbx_description -a _exptl_crystal_grow.method -a _exptl_crystal_grow.pH -a _exptl_crystal_grow.pdbx_details -a _reflns.d_resolution_high -a _reflns_shell.d_res_high -a _symmetry.space_group_name_H-M -a _citation.pdbx_database_id_DOI entries/ > information_from_xrays
# Esto tarda 52 minutos.
# wc -l information_from_xrays
# 255251
# La diferencia con el total de entradas en el PDB, es porque varios archivos contienen más de una entidad 
```

## Verifica integridad de los datos 
Importa los datos extraídos a `R`. Los filtra y genera un par de tablas interesantes.

```{r}
df_01<-read_delim("/home/murphy/doctorado/info.txt", delim = "¿", escape_double = FALSE, col_names = FALSE, trim_ws = TRUE)
df_02 <- df_01 %>%
  rename(
    pdb = X1,
    nde = X2,
    tde = X3,
    ide = X4,
    nom = X5,
    tec = X6,
    peh = X7,
    con = X8,
    rs1 = X9,
    rs2 = 10,
    gpo = X11,
    doi = X12
  )
# Datos para tablas.
tab_gpo<-df_02 %>%
  count(gpo, name = "cta_gpo") %>%
  arrange(desc(cta_gpo))
tab_ide<-df_02 %>%
  count(ide, name = "cta_ide") %>%
  arrange(desc(cta_ide))
# Genera tablas.
kable(tab_gpo) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width=F)
kable(tab_ide) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width=F)
# Guarda esta tabla.
write_excel_csv(tab_ide, "/run/media/murphy/lolita/doctorado/xray/info/tabidebeforefilters.csv")
# Aplica los siguientes filtros con filter de dplyr.
# Filtro 1: que exista solo una entidad en cada entrada.
# Filtro 2: que exista una anotación de pH.
# Filtro 3: que exista una anotación del identificador.
# Filtro 4: que la entrada corresponda a una proteína.
# Filtro 5: que la entrada tenga una buena resolución.
df_03<-df_02 %>% 
  filter(nde=="1" & !is.na(peh) & !is.na(ide) & tde=="polypeptide(L)" & rs1<1.80)
df_04<-df_03 %>%
  add_count(ide, name = "cta_ide")
# Filtro 6: elimina entradas si no hay más de 2 identificadores. 
df_05<-df_04 %>%
  filter(cta_ide>2)
# Añade una nueva columna al df con la desviación estándar del pH por identificador y grupo espacial.
df_06 <-df_05 %>%
  group_by(ide,gpo) %>%
  mutate(sdpH = sd(peh))
# Añade una nueva columna al df con el valor promedio del pH por identificador y grupo espacial.
df_07 <-df_06 %>%
  group_by(ide,gpo) %>%
  mutate(mupH = mean(peh))
# Añade una nueva columna al df con el valor mínimo del pH por identificador y grupo espacial.
df_08 <-df_07 %>%
  group_by(ide,gpo) %>%
  mutate(mnpH = min(peh))
# Añade una nueva columna al df con el valor máximo del pH por identificador y grupo espacial.
df_09 <-df_08 %>%
  group_by(ide,gpo) %>%
  mutate(mxpH = max(peh))
# Añade una nueva columna al df con el intervalo del pH por identificador y grupo espacial.
df_10 <-df_09 %>%
  group_by(ide,gpo) %>%
  mutate(inpH = max(peh)-min(peh))
# Filtro 7: elimina entradas si la desviación estándar del pH es igual a cero o no existe.
df_11<-df_10 %>%
  filter(sdpH!=0)
# Filtro 8: elimina entradas si el intervalo del pH es menor a tres unidades de pH
df_12<-df_11 %>%
  filter(inpH>4)
write_excel_csv(df_12, "/run/media/murphy/lolita/doctorado/xray/info/tabideafterfilters.csv")
ggplot(data=df_12%>%filter(cta_ide>30), aes(x=peh, fill=ide))+geom_histogram(colour="black")+facet_wrap(ide~gpo)+coord_cartesian(ylim = c(0,10)) +theme_bw()+labs(x = "pH", y = "Entradas", fill="Identificador")
setwd("/home/murphy/doctorado/")
ggsave("histogram_pH.pdf", width = 30, height = 25, units = "cm")
ggsave("histogram_pH.png", width = 30, height = 25, units = "cm")
```


